module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'wip',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'domain',
        'application',
        'infrastructure',
        'shared',
        'ai',
        'agents',
        'memory',
        'rag',
        'execution',
        'runner',
        'scheduler',
        'queue',
        'workers',
        'frameworks',
        'api',
        'dashboard',
        'cli',
        'sdk',
        'plugin',
        'auth',
        'security',
        'performance',
        'monitoring',
        'reporting',
        'integrations',
        'ticketing',
        'cicd',
      ],
    ],
    'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
    'header-max-length': [2, 'always', 100],
  },
};
